# -*- coding: utf-8 -*-
"""Linear_regression_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j51suOsV4ydfyHGGgHJJDZxQuwzHU3QW
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Generate dummy data
X = np.array(range(100)).reshape(-1, 1)
y = 3 * X + np.random.randn(100, 1) * 10

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

